require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DirectoryNameCleanupPatternsController do

  # This should return the minimal set of attributes required to create a valid
  # DirectoryNameCleanupPattern. As you add validations to DirectoryNameCleanupPattern, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "pattern" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DirectoryNameCleanupPatternsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all directory_name_cleanup_patterns as @directory_name_cleanup_patterns" do
      directory_name_cleanup_pattern = DirectoryNameCleanupPattern.create! valid_attributes
      get :index, {}, valid_session
      assigns(:directory_name_cleanup_patterns).should eq([directory_name_cleanup_pattern])
    end
  end

  describe "GET show" do
    it "assigns the requested directory_name_cleanup_pattern as @directory_name_cleanup_pattern" do
      directory_name_cleanup_pattern = DirectoryNameCleanupPattern.create! valid_attributes
      get :show, {:id => directory_name_cleanup_pattern.to_param}, valid_session
      assigns(:directory_name_cleanup_pattern).should eq(directory_name_cleanup_pattern)
    end
  end

  describe "GET new" do
    it "assigns a new directory_name_cleanup_pattern as @directory_name_cleanup_pattern" do
      get :new, {}, valid_session
      assigns(:directory_name_cleanup_pattern).should be_a_new(DirectoryNameCleanupPattern)
    end
  end

  describe "GET edit" do
    it "assigns the requested directory_name_cleanup_pattern as @directory_name_cleanup_pattern" do
      directory_name_cleanup_pattern = DirectoryNameCleanupPattern.create! valid_attributes
      get :edit, {:id => directory_name_cleanup_pattern.to_param}, valid_session
      assigns(:directory_name_cleanup_pattern).should eq(directory_name_cleanup_pattern)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DirectoryNameCleanupPattern" do
        expect {
          post :create, {:directory_name_cleanup_pattern => valid_attributes}, valid_session
        }.to change(DirectoryNameCleanupPattern, :count).by(1)
      end

      it "assigns a newly created directory_name_cleanup_pattern as @directory_name_cleanup_pattern" do
        post :create, {:directory_name_cleanup_pattern => valid_attributes}, valid_session
        assigns(:directory_name_cleanup_pattern).should be_a(DirectoryNameCleanupPattern)
        assigns(:directory_name_cleanup_pattern).should be_persisted
      end

      it "redirects to the created directory_name_cleanup_pattern" do
        post :create, {:directory_name_cleanup_pattern => valid_attributes}, valid_session
        response.should redirect_to(DirectoryNameCleanupPattern.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved directory_name_cleanup_pattern as @directory_name_cleanup_pattern" do
        # Trigger the behavior that occurs when invalid params are submitted
        DirectoryNameCleanupPattern.any_instance.stub(:save).and_return(false)
        post :create, {:directory_name_cleanup_pattern => { "pattern" => "invalid value" }}, valid_session
        assigns(:directory_name_cleanup_pattern).should be_a_new(DirectoryNameCleanupPattern)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DirectoryNameCleanupPattern.any_instance.stub(:save).and_return(false)
        post :create, {:directory_name_cleanup_pattern => { "pattern" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested directory_name_cleanup_pattern" do
        directory_name_cleanup_pattern = DirectoryNameCleanupPattern.create! valid_attributes
        # Assuming there are no other directory_name_cleanup_patterns in the database, this
        # specifies that the DirectoryNameCleanupPattern created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DirectoryNameCleanupPattern.any_instance.should_receive(:update_attributes).with({ "pattern" => "MyString" })
        put :update, {:id => directory_name_cleanup_pattern.to_param, :directory_name_cleanup_pattern => { "pattern" => "MyString" }}, valid_session
      end

      it "assigns the requested directory_name_cleanup_pattern as @directory_name_cleanup_pattern" do
        directory_name_cleanup_pattern = DirectoryNameCleanupPattern.create! valid_attributes
        put :update, {:id => directory_name_cleanup_pattern.to_param, :directory_name_cleanup_pattern => valid_attributes}, valid_session
        assigns(:directory_name_cleanup_pattern).should eq(directory_name_cleanup_pattern)
      end

      it "redirects to the directory_name_cleanup_pattern" do
        directory_name_cleanup_pattern = DirectoryNameCleanupPattern.create! valid_attributes
        put :update, {:id => directory_name_cleanup_pattern.to_param, :directory_name_cleanup_pattern => valid_attributes}, valid_session
        response.should redirect_to(directory_name_cleanup_pattern)
      end
    end

    describe "with invalid params" do
      it "assigns the directory_name_cleanup_pattern as @directory_name_cleanup_pattern" do
        directory_name_cleanup_pattern = DirectoryNameCleanupPattern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DirectoryNameCleanupPattern.any_instance.stub(:save).and_return(false)
        put :update, {:id => directory_name_cleanup_pattern.to_param, :directory_name_cleanup_pattern => { "pattern" => "invalid value" }}, valid_session
        assigns(:directory_name_cleanup_pattern).should eq(directory_name_cleanup_pattern)
      end

      it "re-renders the 'edit' template" do
        directory_name_cleanup_pattern = DirectoryNameCleanupPattern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DirectoryNameCleanupPattern.any_instance.stub(:save).and_return(false)
        put :update, {:id => directory_name_cleanup_pattern.to_param, :directory_name_cleanup_pattern => { "pattern" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested directory_name_cleanup_pattern" do
      directory_name_cleanup_pattern = DirectoryNameCleanupPattern.create! valid_attributes
      expect {
        delete :destroy, {:id => directory_name_cleanup_pattern.to_param}, valid_session
      }.to change(DirectoryNameCleanupPattern, :count).by(-1)
    end

    it "redirects to the directory_name_cleanup_patterns list" do
      directory_name_cleanup_pattern = DirectoryNameCleanupPattern.create! valid_attributes
      delete :destroy, {:id => directory_name_cleanup_pattern.to_param}, valid_session
      response.should redirect_to(directory_name_cleanup_patterns_url)
    end
  end

end
